apiVersion: v1
kind: Service
metadata:
  name: cap-frontend-test-service
  labels:
    app: cap-frontend-test
    environment: test
spec:
  selector:
    app: cap-frontend-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP 