apiVersion: v1
kind: Service
metadata:
  name: cap-frontend-service
  labels:
    app: cap-frontend
spec:
  selector:
    app: cap-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP