export const CITIES = [
  { value: "Aracruz", label: "Aracruz", locode: "BR ACZ" },
  { value: "Arapiraca", label: "Arapiraca", locode: "BR ARC" },
  { value: "Belo Horizonte", label: "Belo Horizonte", locode: "BR BHZ" },
  { value: "Boa Vista", label: "Boa Vista", locode: "BR BVB" },
  { value: "Cajazeiras", label: "Cajazeiras", locode: "BR CAJ" },
  { value: "Crato", label: "Crato", locode: "BR CAT" },
  { value: "Cuiabá", label: "Cuiabá", locode: "BR CBA" },
  { value: "Camaçari", label: "Camaçari", locode: "BR CCI" },
  { value: "Cáceres", label: "Cáceres", locode: "BR CCX" },
  { value: "Caracaraí", label: "Caracaraí", locode: "BR CCY" },
  { value: "Contagem", label: "Contagem", locode: "BR CGE" },
  { value: "Campo Grande", label: "Campo Grande", locode: "BR CGR" },
  { value: "Cariacica", label: "Cariacica", locode: "BR CII" },
  { value: "Campo Largo", label: "Campo Largo", locode: "BR CLO" },
  { value: "Camaragibe", label: "Camaragibe", locode: "BR CME" },
  { value: "Corumbá", label: "Corumbá", locode: "BR CMG" },
  { value: "Coxim", label: "Coxim", locode: "BR COX" },
  { value: "Caxias do Sul", label: "Caxias do Sul", locode: "BR CXL" },
  { value: "Cruzeiro do Sul", label: "Cruzeiro do Sul", locode: "BR CZL" },
  { value: "Formosa", label: "Formosa", locode: "BR FMO" },
  { value: "Fortaleza", label: "Fortaleza", locode: "BR FOR" },
  { value: "Gravataí", label: "Gravataí", locode: "BR GRA" },
  { value: "Goiânia", label: "Goiânia", locode: "BR GYN" },
  { value: "Itapipoca", label: "Itapipoca", locode: "BR IIP" },
  { value: "Ilhéus", label: "Ilhéus", locode: "BR IOS" },
  { value: "Ji-Paraná", label: "Ji-Paraná", locode: "BR JPR" },
  { value: "Juazeiro", label: "Juazeiro", locode: "BR JZO" },
  { value: "Manaus", label: "Manaus", locode: "BR MAO" },
  { value: "Maranguape", label: "Maranguape", locode: "BR MGE" },
  { value: "Montes Claros", label: "Montes Claros", locode: "BR MOC" },
  { value: "Mossoró", label: "Mossoró", locode: "BR MOS" },
  { value: "Miranda", label: "Miranda", locode: "BR MRD" },
  { value: "Petrópolis", label: "Petrópolis", locode: "BR PES" },
  {
    value: "Palmeira dos Índios",
    label: "Palmeira dos Índios",
    locode: "BR PIS",
  },
  { value: "Porto Alegre", label: "Porto Alegre", locode: "BR POA" },
  { value: "Rio Branco", label: "Rio Branco", locode: "BR RBR" },
  { value: "Rio de Janeiro", label: "Rio de Janeiro", locode: "BR RIO" },
  {
    value: "Ribeirão das Neves",
    label: "Ribeirão das Neves",
    locode: "BR RNV",
  },
  { value: "São Cristóvão", label: "São Cristóvão", locode: "BR SCV" },
  { value: "Serra", label: "Serra", locode: "BR SER" },
  { value: "Sinop", label: "Sinop", locode: "BR SIN" },
  {
    value: "São João de Meriti",
    label: "São João de Meriti",
    locode: "BR SJM",
  },
  { value: "São Leopoldo", label: "São Leopoldo", locode: "BR SLO" },
  { value: "Sobral", label: "Sobral", locode: "BR SOB" },
  { value: "Sorocaba", label: "Sorocaba", locode: "BR SOR" },
  { value: "Tangará da Serra", label: "Tangará da Serra", locode: "BR TSE" },
  {
    value: "Vitória de Santo Antão",
    label: "Vitória de Santo Antão",
    locode: "BR VDS",
  },
  { value: "Abaetetuba", label: "Abaetetuba", locode: "BR ATB" },
  { value: "Cametá", label: "Cametá", locode: "BR CMA" },
  { value: "Parintins", label: "Parintins", locode: "BR PIN" },
  { value: "Tarauacá", label: "Tarauacá", locode: "BR TAA" },
];

export const ADAPTA_BRASIL_API = "https://adapta-brasil-api.replit.app";
