name: CAP Frontend Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - '**'
      - '.github/workflows/develop.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      REPOSITORY: open-earth-foundation/cap-frontend
      VITE_AWS_REGION: us-east-2
      VITE_AWS_S3_BUCKET_ID: openearth.cap
      VITE_API_URL: http://cap-api:8080
      VITE_PLAN_CREATOR_URL: https://cap-plan-creator.openearth.dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Git commit hash
        id: vars
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            VITE_AWS_REGION=${{ env.VITE_AWS_REGION }}
            VITE_AWS_S3_BUCKET_ID=${{ env.VITE_AWS_S3_BUCKET_ID }}
            VITE_API_URL=${{ env.VITE_API_URL }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ steps.vars.outputs.commit_hash }}
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_EKS_DEV_USER }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_EKS_DEV_USER }}
      EKS_DEV_NAME: ${{ secrets.EKS_DEV_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: Creating kubeconfig file
        run: aws eks update-kubeconfig --name ${{secrets.EKS_DEV_NAME}} --region us-east-1

      - name: Testing connection to EKS
        run: kubectl get pods -n default

      - name: Re-deploying service
        run: |
          kubectl rollout restart deployment cap-frontend -n default
